import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(19823626-F6EA-472F-9AA3-1B2CA0693E53),
	pointer_default(unique)
]
interface IMyMath : IUnknown{
	[] HRESULT Test(void);
};
[
	uuid(68A502DA-EEB1-4B25-A0A4-3118922CBFE4),
	version(1.0),
]
library ComTestLib
{
	importlib("stdole2.tlb");
	[
		uuid(B379BB26-80E6-4DCB-AD82-8F46BA81BBCF)		
	]
	coclass MyMath
	{
		[default] interface IMyMath;
	};
};

